<script lang="ts">
 import PageShell from '$lib/components/PageShell.svelte'; import {listings,orders,wallet} from '$lib/api'; import {session} from '$lib/stores/session'; import type {Listing,Order,Transaction} from '$lib/types';
 let mine=$state<Listing[]>([]), orderHistory=$state<Order[]>([]), transactions=$state<Transaction[]>([]), balance=$state<number|null>(null), loading=$state(true), error=$state('');
 $effect(()=>{if(!$session)return;loading=true;Promise.all([listings.all(),orders.all(),wallet.get(),wallet.transactions()]).then(([lp,os,w,tx])=>{mine=(lp.items||[]).filter(i=>i.ownerId===$session?.id||i.producerName===$session?.name);orderHistory=os||[];balance=w.balanceSats;transactions=tx||[]}).catch(e=>error=e instanceof Error?e.message:'Unable to load your dashboard.').finally(()=>loading=false)});
 const date=(v?:string)=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
</script>
<PageShell eyebrow="YOUR LEDGER" title="Welcome back, {$session?.name?.split(' ')[0]||'there'}. ">
{#if loading}<p class="state">Loading your personal ledger…</p>{:else if error}<p class="alert">{error}</p>{:else}
<div class="dash-grid"><div class="metric"><span>Wallet balance</span><strong>{balance===null?'—':balance.toLocaleString()} sats</strong><small><a href="/wallet">Open wallet ↗</a></small></div><div class="metric"><span>Listings created</span><strong>{mine.length}</strong><small><a href="/dashboard/listings/new">Create listing ↗</a></small></div><div class="metric"><span>Orders & activity</span><strong>{orderHistory.length+transactions.length}</strong><small>Across your account</small></div></div>
<div class="dashboard-columns"><section class="form-card dashboard-section"><div class="dashboard-head"><div><p class="eyebrow">YOUR LISTINGS</p><h2>{mine.length?'Published inventory':'No listings yet'}</h2></div><a class="text-link" href="/dashboard/listings/new">Add listing ↗</a></div>{#if mine.length}{#each mine as item}<a class="dash-listing" href={`/marketplace/${item.id}`}><span class="listing-mark">♻</span><span><strong>{item.title}</strong><small>{item.quantity} {item.unit} · {item.location}</small></span><span class="status">{item.status||'Active'}</span></a>{/each}{:else}<p class="state">Your published listings will appear here.</p>{/if}</section>
<section class="form-card dashboard-section"><p class="eyebrow">ACCOUNT DETAILS</p><h2>Personal profile</h2><div class="profile-grid"><span>Name<strong>{$session?.name||'—'}</strong></span><span>Email<strong>{$session?.email||'—'}</strong></span><span>Role<strong>{$session?.role||'—'}</strong></span><span>Location<strong>{$session?.location||'Not added'}</strong></span><span>Business<strong>{$session?.businessName||'Not added'}</strong></span><span>Rating<strong>{$session?.rating?`${$session.rating} / 5`:'No ratings yet'}</strong></span></div><a class="btn ghost" href="/settings">Edit profile ↗</a></section></div>
<div class="dashboard-columns lower"><section class="form-card dashboard-section"><p class="eyebrow">TRANSACTION HISTORY</p><h2>{transactions.length?'Recent transactions':'No transactions yet'}</h2>{#if transactions.length}{#each transactions.slice(0,6) as tx}<div class="history-row"><span>{tx.type.replace('_',' ')}</span><strong>{tx.amountSats.toLocaleString()} sats</strong><small>{tx.status} · {date(tx.createdAt)}</small></div>{/each}{:else}<p class="state">Wallet deposits and payments will show here.</p>{/if}</section><section class="form-card dashboard-section"><p class="eyebrow">ORDER HISTORY</p><h2>{orderHistory.length?'Your orders':'No orders yet'}</h2>{#if orderHistory.length}{#each orderHistory.slice(0,6) as order}<div class="history-row"><span>Order {order.id.slice(-6)}</span><strong>{order.amountSats.toLocaleString()} sats</strong><small>{order.status} · {date(order.createdAt)}</small></div>{/each}{:else}<p class="state">Orders you place will show here.</p>{/if}<a class="text-link" href="/marketplace">Browse marketplace ↗</a></section></div>{/if}</PageShell>
